Repository UNLV-CS472-672/2024-S-GROUP8-CW, pull requests merged in 2024-04, with the labels that each got.

#92 Added Phases (Defense, Attack, Build)
  Crypto Wars/Assets/Scripts/PlayerScript.cs
  Crypto Wars/Assets/Scripts/TurnMaster.cs
Labels: enhancement, implementation

#99 Add functionality for Victory Screen
  Crypto Wars/Assets/Scripts/GUI/VictoryScreen.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/VictoryScreenTest.cs
Labels: enhancement, implementation

#98 Refactor TurnMaster and Player classes for enhanced phase management …
  Crypto Wars/Assets/Scripts/Test_EditMode/PlayerScriptTest.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/TurnMasterTest.cs
  Crypto Wars/Assets/Scripts/TurnMaster.cs
  PR_Checklist.md
Labels: enhancement

#115 Implemented HandManager Class
  Crypto Wars/Assets/Scripts/GUI/HandManager.cs
  Crypto Wars/Assets/Scripts/PlayerController.cs
  Crypto Wars/Assets/Scripts/PlayerScript.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/PlayerListTest.cs.meta
Labels: implementation

#112 added comprehensive unit testing to increase code coverage - buildingRegistry
  Crypto Wars/Assets/Scripts/Test_EditMode/BuildingRegistryTest.cs
Labels: test coverage

#113 added comprehensive unit testing to increase code coverage - cardRegi…
  Crypto Wars/Assets/Scripts/Test_EditMode/CardRegistryTest.cs
Labels: test coverage

#134 fixBuildBttnTest
  Crypto Wars/Assets/Scripts/GUI/BuildButtonScript.cs
  Crypto Wars/Assets/Scripts/GUI/BuildButtonScript.cs.meta
  Crypto Wars/Assets/Scripts/Test_EditMode/BuildButtonTest.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/BuildButtonTest.cs.meta
  Crypto Wars/Assets/Scripts/Test_PlayMode/BuildButtonScriptTest.cs
Labels: test coverage
