Repository UNLV-CS472-672/2024-S-GROUP8-CW, pull requests merged in 2024-03, with the labels that each got.

#18 Add Abstract CardClass
  Crypto Wars/Assets/Scripts/CardClass_Abstract.cs
  Crypto Wars/Assets/Scripts/CardClass_Abstract.cs.meta
Labels: implementation

#30 Added functionality for GameManager
  Crypto Wars/Assets/Scripts/GameManager.cs
  Crypto Wars/Assets/Scripts/GameManager.cs.meta
Labels: implementation

#36 Unity Compilation Error (PlayerScript) - Fix syntax errors
  Crypto Wars/Assets/Scripts/PlayerScript.cs
Labels: bug

#34 Inventory Class
  Crypto Wars/Assets/Scripts/Inventory.cs
  Crypto Wars/Assets/Scripts/Inventory.cs.meta
Labels: implementation

#24 Fixing Pipeline
  .github/workflows/unity_ci.yml
  Crypto Wars/Assets/Scripts/buildingRegistry.cs
  Crypto Wars/Assets/Scripts/cardRegistry.cs
Labels: pipeline issue / request

#32 added 3 files (UnitType, buildingScript, cardScript) to address Issue #28
  Crypto Wars/Assets/Scripts/UnitType.cs
  Crypto Wars/Assets/Scripts/cardRegistry.cs
Labels: implementation

#39 Add Unity Test Framework (UTF)
  Crypto Wars/Assets/Scripts/Test_EditMode.meta
  Crypto Wars/Assets/Scripts/Test_EditMode/ExampleTestScript.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/ExampleTestScript.cs.meta
  Crypto Wars/Assets/Scripts/Test_EditMode/Tests.asmdef
  Crypto Wars/Assets/Scripts/Test_EditMode/Tests.asmdef.meta
  Crypto Wars/Assets/Scripts/Test_PlayMode.meta
  Crypto Wars/Assets/Scripts/Test_PlayMode/NewTestScript.cs
  Crypto Wars/Assets/Scripts/Test_PlayMode/NewTestScript.cs.meta
  Crypto Wars/Assets/Scripts/Test_PlayMode/Tests 1.asmdef
  Crypto Wars/Assets/Scripts/Test_PlayMode/Tests 1.asmdef.meta
Labels: test coverage

#63 Add test coverage for PlayerScript
  Crypto Wars/Assets/Scripts/Scripts.asmref
  Crypto Wars/Assets/Scripts/Scripts.asmref.meta
  Crypto Wars/Assets/Scripts/Test_EditMode/testPlayerScript.cs
  Crypto Wars/Assets/Scripts/Test_EditMode/testPlayerScript.cs.meta
Labels: test coverage

#67 removed build from workflow jobs for now
  .github/workflows/unity_ci.yml
Labels: pipeline issue / request
